name: Ejecutar Newman todos los días a las 6 AM

on:
  schedule:
    - cron: '0 6 * * *'  # Esto se ejecutará todos los días a las 6 AM UTC
  workflow_dispatch:  # Esto permite ejecutar el flujo manualmente si lo deseas

jobs:
  run_newman_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Ejecutar las pruebas de Newman
        run: newman run Uvilor_reporte.postman_collection.json --environment uvilor-labs.postman_environment.json --reporters cli,html --reporter-html-export newman_report.html

      - name: Subir reporte a S3 (opcional)
        run: |
          aws s3 cp newman_report.html s3://YOUR_BUCKET_NAME/ --region YOUR_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
