name: Ejecutar Newman todos los días a las 6 AM

on:
  schedule:
    - cron: '0 6 * * *'  
  workflow_dispatch:  

jobs:
  run_newman_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Consultar repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalar Newman
        run: npm install -g newman

      - name: Ejecutar las pruebas de newman
        run: newman run Uvilor_reporte.postman_collection.json --environment uvilor-labs.postman_environment.json --reporters cli,html --reporter-html-export newman_report.html
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Upload report to S3
        run: aws s3 cp newman/ s3://newman-uvilor/ --recursive
