name: Ejecutar Newman todos los días a las 6 AM

on:
  schedule:
    - cron: '0 6 * * *'  
  workflow_dispatch:  

jobs:
  run_newman_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Consultar repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalar Newman
        run: npm install -g newman newman-reporter-html newman-reporter-htmlextra

      - name: Crear carpeta para reportes
        run: mkdir -p newman

      - name: Correr newman
        env:
          USERS_ARRAY: ${{ secrets.USERS_ARRAY }}
        run: |
          # Guardar la variable JSON en un archivo y verificar su contenido
          printf "%s" "${USERS_ARRAY}" > users.json

          echo "Verificando contenido de users.json:"
          cat users.json
          jq . users.json || { echo "Error: JSON inválido"; exit 1; }

          # Procesar cada usuario
          jq -c '.[]' users.json | while read -r user; do
            ctid=$(echo "$user" | jq -r '.ctid')
            username=$(echo "$user" | jq -r '.username')

            echo "Ejecutando Newman para usuario: $username, CTID: $ctid"

            # Asegurar que la carpeta de reportes existe
            mkdir -p "newman/${ctid}"
            report_path="newman/${ctid}/newman_report.html"

            # Ejecutar Newman y generar el reporte en la carpeta correcta
            newman run Uvilor_reporte.postman_collection.json \
              --environment uvilor-labs.postman_environment.json \
              --global-var "credentials=$user" \
              --reporters cli,html,htmlextra \
              --reporter-html-export "${report_path}" -n 1 

            # Verificar si el archivo fue generado
            if [[ -f "${report_path}" ]]; then
              echo "Reporte generado exitosamente: ${report_path}"
            else
              echo "Error: No se generó el reporte en ${report_path}"
              exit 1
            fi
          done

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload report to S3
        run: |
          echo "Verificando contenido de la carpeta newman/"
          ls -R newman/

          echo "Subiendo reportes a S3..."
          aws s3 cp newman/ s3://newman-uvilor/ --recursive
